version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: site1
    ports:
      - '8080:80'
    volumes:
      - .:/var/www/html
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
